Load a file from Disk
rrickfox/traffic-sim pull request #101
Opened 2020-03-10 09:53 UTC by Sidlertime

choose a file you to load

close #79

2020-03-10 18:27 UTC, funketh commented
`Assets/StandaloneFileBrowser/` sollte in  `Assets/Plugins/StandaloneFileBrowser/` sein

2020-03-10 18:28 UTC, funketh commented
Warum hat sich was an `Assets/Plugins/NuGet/Editor/DotNetZip.dll` und ` Assets/Plugins/NuGet/Editor/NugetForUnity.dll `geändert?

2020-03-10 18:41 UTC, Sidlertime commented
Bei den DLLs nur dass ich sie zu gut LFS hinzugefügt HABE und das mit dem Plugin ok, aber ich werde hier so oder noch einiges änrern

2020-03-13 14:27 UTC, funketh requested changes
die menu szene sollte entfernt werden, wenn sie jetzt redundant ist

2020-03-13 14:43 UTC, funketh approved these changes

2020-03-13 15:06 UTC, RichardKarlFuchs approved these changes

2020-03-13 18:01 UTC, funketh approved these changes
Lasse das approval mal da, falls du die sachen bis heut abend nicht gefixt kriegst und mergen willst

2020-03-13 18:01 UTC, funketh commented on Assets/Scripts/Interface/Manager.cs
> +    public class Manager : MonoBehaviour
'Manager' ist ziemlich unspezifisch. Wir wärs mit SimulationManager oder so?

2020-03-13 18:01 UTC, funketh commented on Assets/Scripts/Interface/Manager.cs
> +        public SaveLoader saveLoader;
saveLoader wird nicht genutzt

2020-03-13 18:01 UTC, funketh commented on Assets/Scripts/Saves/SaveLoader.cs
> +            catch { }
Bitte nur spezifische Fehler catchen, ein catch-all ist nicht so toll (außer du loggst den fehler).

2020-03-13 18:47 UTC, rrickfox commented on Assets/Scripts/Interface/Manager.cs
> +    public class Manager : MonoBehaviour
Wie wäre es mit `SimulationController`? ;)

2020-03-13 19:19 UTC, merged