Feature/road spawner
rrickfox/traffic-sim pull request #17
Opened 2020-01-19 21:33 UTC by rrickfox

Klasse um bestehende Straßen grafisch anzuzeigen

2020-01-19 22:23 UTC, funketh commented
#12

2020-01-20 20:08 UTC, RobertEggert requested changes

2020-01-20 20:08 UTC, RobertEggert commented on Assets/Scripts/DataTypes/Road.cs
> +        public Vector2 GetPosition(float positionOnRoad, Direction direction, float lane)
Kommentar fehlt

2020-01-20 20:08 UTC, RobertEggert commented on Assets/Scripts/DataTypes/Road.cs
> +                position += forward * offset;
berechnet nicht die eigentliche Position, stattdessen `right`

2020-01-20 21:43 UTC, 1NG3M4R commented on Assets/Scripts/DataTypes/Car.cs
> -        // true if from start to finish
passt denke ich

2020-01-21 14:57 UTC, rrickfox commented on Assets/Scripts/DataTypes/Road.cs
> +        public Vector2 GetPosition(float positionOnRoad, Direction direction, float lane)
Fixed: b658a39

2020-01-21 14:58 UTC, rrickfox commented on Assets/Scripts/DataTypes/Road.cs
> +                position += forward * offset;
Solved: b658a39

2020-01-27 09:24 UTC, Shafma approved these changes

2020-01-27 20:26 UTC, 1NG3M4R commented on Assets/Scripts/RoadSpawner.cs
> +        _roads.Add(tempRoad);
tempRoad ist kein guter Name

2020-01-27 20:40 UTC, 1NG3M4R approved these changes
Hauptdateien sind nach marginalen Änderungen in Ordnung

2020-01-27 21:31 UTC, RobertEggert approved these changes

2020-01-27 23:37 UTC, merged