Adding a Camera Movement to the Main Camera
rrickfox/traffic-sim pull request #28
Opened 2020-01-21 21:12 UTC by Sidlertime

- Right-Click to turn
- WASD to move / mouse to the edge
- MouseWheel to zoom

2020-01-22 17:41 UTC, RichardKarlFuchs requested changes
Bitte Möglichkeit hinzufügen, die Plattform aus Vogelperspektive zu betrachten.
Bug: Es ist Möglich die Grenzen der Plattform zu überfliegen.

2020-01-22 17:41 UTC, rrickfox commented on Assets/Scripts/CameraMovement.cs
> +        camDistance = Mathf.Clamp(camDistance, minZoom, maxZoom);
camDistance ist von Default kleiner als minZoom und wird daher sofort auf minZoom gesetzt.

2020-01-22 17:41 UTC, rrickfox commented on Assets/Scripts/CameraMovement.cs
> +    }
Ist in der Praxis nicht zu wahrnehmbar, sorgt dafür, dass die Kamera sich schnell wegbewegt, wenn die maus das Fenster verlässt (anderer Bildschirm, verändern der Einstellungen etc.)

2020-01-22 17:41 UTC, rrickfox commented on Assets/Scripts/CameraMovement.cs
> +    public float maxZoom = 20f;
größere Zoom Unterschiede gewünscht, bisher ist Zoom kaum spürbar

2020-01-23 21:25 UTC, RichardKarlFuchs approved these changes
Vllt bessere Defaultwerte: Flyspeed = 1, Turnspeed = 0.5, ZoomSpeed = 15

2020-01-23 23:00 UTC, funketh requested changes
* alle dieser Klassen in einen `Camera` namespace packen
* nen Unterstrich vor jeden Namen bei privaten Attributen #3

Bei mir funktioniert es übrigens nicht, kriege das Warning:
```
The referenced script on this Behaviour (Game Object 'SimulationController') is missing!
```

2020-01-23 23:00 UTC, funketh commented on Assets/Scripts/Camera/BirdCamera.cs
> +using System.Collections.Generic;
redundant

2020-01-23 23:00 UTC, funketh commented on Assets/Scripts/Camera/CameraManager.cs
> +﻿using System.Collections;
redundant

2020-01-23 23:00 UTC, funketh commented on Assets/Scripts/Camera/FreeCamera.cs
> +using System.Collections.Generic;
redundant

2020-01-23 23:00 UTC, funketh commented on Assets/Scripts/Camera/FreeCamera.cs
> +                Debug.Log("max Angle reached");
Logs sind zu teuer, als dass sie jedes FixedUpDate ausgeführt werden können.
Scheint hier aber OK zu sein, da sie ja nur beim minimum und maximum des Winkels aufgerufen werden, oder?
https://github.com/JetBrains/resharper-unity/wiki/Avoid-usage-of-Debug.Log-methods-in-performance-critical-context

2020-01-23 23:00 UTC, funketh commented on Assets/Scripts/Camera/CameraManager.cs
> +        }
zu nem foreach loop konvertieren (besonders relevant bei Listen, da jeder Index access O(N) kostet, während man beim foreach für jede iteration nur 1 element weitergeht)

2020-01-26 09:57 UTC, funketh requested changes
* Ordner zu `Cameras/` umbenennen, damit er zum Namen vom namespace passt

2020-01-26 09:57 UTC, funketh commented on Assets/Scripts/Camera/FreeCamera.cs
> +                }
inkonsistente geschweifte Klammern

2020-01-26 09:57 UTC, funketh commented on Assets/Scripts/Camera/BirdCamera.cs
> +        }
Das muss nicht jedes Update aufgerufen werden. Finde aber auch keinen Weg, etwas nur beim aktivieren der Kamera zu tun.

2020-01-26 09:57 UTC, funketh commented on Assets/Scripts/Camera/CameraManager.cs
> +
inkonsistente leere Zeile

2020-01-26 09:57 UTC, funketh commented on Assets/Scripts/Camera/CameraManager.cs
> +        int _activeCam;
sollte vlt eher `_activeCamIndex` heißen

2020-01-26 09:57 UTC, funketh commented on Assets/Scripts/Camera/CameraManager.cs
> +            }
* `i` bleibt hier stets auf `0`
* alternative lösung ohne loop wäre so was:
```cs
void ChangeCam(int newCamIndex)
{
    cams[_activeCamIndex].enabled = false;
    _activeCamIndex = newCamIndex;
    cams[_activeCamIndex].enabled = true;
}
```
Dann würde man den `_activeCamIndex` nur hier verändern und woanders den neuen Index einfach hier als Parameter eingeben

2020-01-26 17:02 UTC, funketh reviewed
* soweit ich sehe hat es keinen Mehrwert, dass `_newCamIndex` nen eigenes Feld ist, statt nem Parameter für `ChangeCam()`, oder?

2020-01-28 20:35 UTC, funketh approved these changes

2020-01-29 17:30 UTC, merged