Feature/road shape
rrickfox/traffic-sim pull request #64
Opened 2020-02-03 23:12 UTC by rrickfox

Bisher noch ohne Mesh

2020-02-04 09:52 UTC, Sidlertime approved these changes
Vielleicht in einer invertierungssache: könnte sein dass da immernoch 
foreach curve in reversedcurves
Steht, müsste aber in curves sein

2020-02-04 10:48 UTC, rrickfox commented
> 
> 
> Vielleicht in einer invertierungssache: könnte sein dass da immernoch
> foreach curve in reversedcurves
> Steht, müsste aber in curves sein

Erledigt, ce9f029

2020-02-04 12:44 UTC, funketh requested changes

2020-02-04 12:44 UTC, funketh commented on Assets/Scripts/DataTypes/Edges/BezierCurve.cs
> +        }
was ist der sinn von `lastPoint`?

2020-02-04 12:44 UTC, funketh commented on Assets/Scripts/DataTypes/Edges/RoadShape.cs
> +        public RoadPoint endingPoint;
welchen Sinn hat `endingPoint`? (wird nie genutzt)

2020-02-04 12:48 UTC, funketh submitted a review, later dismissed
Der Code sollte allgemein kommentiert werden

2020-02-05 16:04 UTC, funketh commented
klär mal die merge-konflikte ab

2020-02-05 18:00 UTC, funketh commented
Die performance der simulation ist bei mir durch die kurve immens gesunken.
Wäre es nicht sinnvoller, ein einziges rundes 3D Objekt zu nutzen, anstatt manuell sehr viele Würfel zu spawnen? (Ist das das was du mit Mesh meinst? Kenne mich da nicht aus)

2020-02-05 19:13 UTC, rrickfox commented
Performance sollte durch das verwenden von einem Mesh wieder steigen. Im Moment werden halt die 7000 Würfel, die eine Straße darstellen, alle vollständig und einzeln gerendert, anstatt dass es nur ein Straßenobjekt gibt.

2020-02-05 23:55 UTC, funketh approved these changes

2020-02-06 00:23 UTC, merged