Add traffic lights
rrickfox/traffic-sim pull request #97
Opened 2020-03-07 21:11 UTC by Shafma

2020-03-07 21:13 UTC, funketh requested changes

2020-03-07 21:13 UTC, funketh commented on Assets/Scripts/DataTypes/TrafficLight.cs
> +                }
switch statement nutzen

2020-03-07 21:18 UTC, Shafma commented on Assets/Scripts/DataTypes/TrafficLight.cs
> +                }
Wie unten?

2020-03-07 21:21 UTC, funketh commented on Assets/Scripts/DataTypes/TrafficLight.cs
> +                }
genau

2020-03-07 21:21 UTC, Shafma commented on Assets/Scripts/DataTypes/TrafficLight.cs
> +                }
Das war der Plan.

2020-03-07 21:28 UTC, funketh requested changes

2020-03-07 21:28 UTC, funketh commented on Assets/Scripts/DataTypes/TrafficLight.cs
> +                }
Bitte nen Tupel/Struct nutzen für sowas, kein Array.

2020-03-11 19:54 UTC, funketh requested changes

2020-03-11 19:54 UTC, funketh commented on Assets/Scripts/DataTypes/Edges/ITrack.cs
> +        [CanBeNull] TrafficLight light { get; set; }
Bitte das CanBeNull weglassen, weil dafür Jetbrains libraries installiert sein müssen (außerdem bringt das nur was wenn man es konsistent überall im code nutzt)

2020-03-11 19:54 UTC, funketh commented on Assets/Scripts/DataTypes/TrafficLight.cs
> +        public Tuple<int, int?> State
properties schreiben wir auch klein (#3). Würde aber state generell einfach zu nem Datentyp machen (also kein enum):
```cs
class LightState
{
    Speed velocity { get; }
    Length? stoppingDistance { get; }
}
class YellowLight : LightState
{
    // constructor, in dem alles berechnet wird und so
}
// ...
```

2020-03-11 19:54 UTC, funketh commented on Assets/Scripts/Saves/Serializers.cs
> +            public Dictionary<TrafficLight.LightState, int> throughFrequency { get; set; }
Das müsste dann zu drei hardgecodeten properties werden, wen der obere Vorchlag durchgesetzt wird (liegt an limitierungen von c#)

2020-03-13 17:09 UTC, Shafma commented on Assets/Scripts/DataTypes/Edges/ITrack.cs
> +        [CanBeNull] TrafficLight light { get; set; }
Ist ja auch nur temporär

2020-03-14 02:10 UTC, Sidlertime approved these changes

2020-03-14 02:25 UTC, funketh approved these changes

2020-03-14 04:59 UTC, merged